### ISSUE TITLE
Fail to load all of Otto's animation assets

### ISSUE THREAD

**Issue by C132** [Unity-Technologies/otto#3]
I keep getting these errors on all of Otto's animation files. I'm in 2019.2.0f1 (an only slightly higher version of unity than the project is currently in). I've reimported all assets and the specific asset but nothing seems to resolve this for me rendering the project unusable. 

otto-master/otto-master/Assets/Models/Otto/Animation/Item_PocketDrink.anim' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Assets affected; Item_GrabDrink, GrabEat, GrabPocket, GrabPocket 1, PocketDrink, PocketEat.

**Comment by amirebrahimi** [comment]
We haven't updated those anims in 5 months, so I'm doubtful we've introduced a different serialized version. Did you by any chance open this project in a newer version of Unity and then downgrade it? Also, are these showing as errors or as warnings? Do the animations run?

**Comment by C132** [comment]
File doesn't import - shown as an unknown file. 

I'm now noticing the notice to not download the zip and instead do a clone - I don't have a git client on this PC but will try that when I get to my other PC. 

The project was opened from a fresh unzip of the project. 

They are errors that essentially cause the animations files to act as if they were corrupt.

**Comment by amirebrahimi** [comment]
Yes, this is your problem. Unfortunately, we can't disable the download link from github, but it is necessary to clone from git because of largefiles usage. I'll create an issue to explore options to solve this often encountered problem.
