### ISSUE TITLE
 The type or namespace name '*****' could not be found

### ISSUE THREAD

**Issue by 704567780** [Unity-Technologies/otto#7]
I use unity 2019.2.17f1 version.
but the project  has some erros ,
"The type or namespace name 'Domains' does not exist in the namespace 'AI.Planner' ",
"The type or namespace name ''StateData'' does not exist in the namespace 'AI.Planner'"
How should I solve this problem？

**Comment by amirebrahimi** [comment]
Are you attempting to use the latest AI Planner package with this project or did you clone it as is?
https://github.com/Unity-Technologies/otto#note-otto-has-not-been-updated-to-use-version-020-of-the-ai-planner-yet
